### PR TITLE
added linkedin and github of members.

### PR DESCRIPTION
**Pull request by onlybond**
# Closes issue #7  

- added members linkedin and github
- couldn't find some of the members linkedin and github i have filled those spaces with mock sites of linkedin and github.

### CODE REVIEW

**Comment by Shinjan-saha** [comment]
@onlybond Please do the pull once it is not showing the latest changes which is done

**Comment by onlybond** [comment]
please check the preview and lemme know, which changes are not getting reflected

**Comment by komal-agarwal5** [comment]
@onlybond the faq and stats changes are not visible.U need to sync your fork and do git pull.
Also for the ones whose account you could find out try adding their images also in the profile card

**Comment by Shinjan-saha** [comment]
@onlybond  are you adding the images as asked by @komal-agarwal5

**Pull request closed without merging**
