### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by TechnicallyKiller**

### CODE REVIEW

**Comment by TechnicallyKiller** [comment]
Now kindly check

**Comment by Shinjan-saha** [comment]
Screenshot_20241026-200448_Chrome
It looks same where did you made the Change?

**Comment by TechnicallyKiller** [comment]
please check now

**Comment by Shinjan-saha** [comment]
Screenshot_20241027-112246_Chrome
Home page is not all looking Good in Mobile version there in an underflow problem there are 2 navbar & also pull once before creating an PR changes in Contact page is not up to date with the latest Changes

**Comment by Shinjan-saha** [comment]
@TechnicallyKiller are you working on it?

**Comment by Shinjan-saha** [comment]
@TechnicallyKiller  since the PR is been inactive for a time we are closing it

**Pull request closed without merging**
