### PR TITLE
Added member cards with dummy info 

### PR DESCRIPTION
**Pull request by Snehalgupta-07**
Screenshot (97)
Screenshot (98)

### CODE REVIEW

**Comment by komal-agarwal5** [comment]
@Snehalgupta-07 Some changes are needed:
1)The navbar layout is getting distorted
2)Other pages boxes and other layouts are getting distorted
It is probably happening due to some CSS naming that is clashing with the other components. Please fix these.
Egs:
Screenshot 2024-10-11 003004
Screenshot 2024-10-11 003017

**Comment by Snehalgupta-07** [comment]
Screenshot (100)
Screenshot (99)
 Fixed!!

**Comment by Shinjan-saha** [comment]
@Snehalgupta-07 can you please improve the design of the cards like please add some color scheme to the Cards & also use Linkdln & Github Icons

**Comment by Snehalgupta-07** [comment]
Screenshot (104)
Added icons and tailwind css

**Comment by Shinjan-saha** [comment]
Screenshot_20241011-122345_Google
Please made Good Profile card like this or Similar to this 
Check the Figma File for the Color Scheme

**Comment by Snehalgupta-07** [comment]
Screenshot (110)
Is this fine?

**Comment by Shinjan-saha** [comment]
@Snehalgupta-07 if possible use a glass like background  effect instead of plane solid color as background

**Pull request merged**
